#!/bin/bash
./allocate -f generated-tests/data0.txt -s SJF -m best-fit -q 3 | diff - generated-tests/output0.txt
./allocate -f generated-tests/data1.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output1.txt
./allocate -f generated-tests/data2.txt -s RR -m best-fit -q 3 | diff - generated-tests/output2.txt
./allocate -f generated-tests/data3.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output3.txt
./allocate -f generated-tests/data4.txt -s SJF -m best-fit -q 3 | diff - generated-tests/output4.txt
./allocate -f generated-tests/data5.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output5.txt
./allocate -f generated-tests/data6.txt -s RR -m infinite -q 3 | diff - generated-tests/output6.txt
./allocate -f generated-tests/data7.txt -s SJF -m infinite -q 1 | diff - generated-tests/output7.txt
./allocate -f generated-tests/data8.txt -s RR -m infinite -q 3 | diff - generated-tests/output8.txt
./allocate -f generated-tests/data9.txt -s SJF -m infinite -q 1 | diff - generated-tests/output9.txt
./allocate -f generated-tests/data10.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output10.txt
./allocate -f generated-tests/data11.txt -s SJF -m infinite -q 3 | diff - generated-tests/output11.txt
./allocate -f generated-tests/data12.txt -s RR -m infinite -q 2 | diff - generated-tests/output12.txt
./allocate -f generated-tests/data13.txt -s RR -m infinite -q 2 | diff - generated-tests/output13.txt
./allocate -f generated-tests/data14.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output14.txt
./allocate -f generated-tests/data15.txt -s SJF -m infinite -q 2 | diff - generated-tests/output15.txt
./allocate -f generated-tests/data16.txt -s RR -m infinite -q 1 | diff - generated-tests/output16.txt
./allocate -f generated-tests/data17.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output17.txt
./allocate -f generated-tests/data18.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output18.txt
./allocate -f generated-tests/data19.txt -s RR -m infinite -q 2 | diff - generated-tests/output19.txt
./allocate -f generated-tests/data20.txt -s RR -m best-fit -q 1 | diff - generated-tests/output20.txt
./allocate -f generated-tests/data21.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output21.txt
./allocate -f generated-tests/data22.txt -s SJF -m infinite -q 2 | diff - generated-tests/output22.txt
./allocate -f generated-tests/data23.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output23.txt
./allocate -f generated-tests/data24.txt -s RR -m best-fit -q 3 | diff - generated-tests/output24.txt
./allocate -f generated-tests/data25.txt -s SJF -m infinite -q 2 | diff - generated-tests/output25.txt
./allocate -f generated-tests/data26.txt -s RR -m infinite -q 2 | diff - generated-tests/output26.txt
./allocate -f generated-tests/data27.txt -s RR -m best-fit -q 3 | diff - generated-tests/output27.txt
./allocate -f generated-tests/data28.txt -s SJF -m best-fit -q 3 | diff - generated-tests/output28.txt
./allocate -f generated-tests/data29.txt -s RR -m infinite -q 1 | diff - generated-tests/output29.txt
./allocate -f generated-tests/data30.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output30.txt
./allocate -f generated-tests/data31.txt -s SJF -m infinite -q 2 | diff - generated-tests/output31.txt
./allocate -f generated-tests/data32.txt -s SJF -m infinite -q 1 | diff - generated-tests/output32.txt
./allocate -f generated-tests/data33.txt -s SJF -m infinite -q 1 | diff - generated-tests/output33.txt
./allocate -f generated-tests/data34.txt -s RR -m infinite -q 3 | diff - generated-tests/output34.txt
./allocate -f generated-tests/data35.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output35.txt
./allocate -f generated-tests/data36.txt -s RR -m best-fit -q 2 | diff - generated-tests/output36.txt
./allocate -f generated-tests/data37.txt -s SJF -m infinite -q 3 | diff - generated-tests/output37.txt
./allocate -f generated-tests/data38.txt -s RR -m infinite -q 2 | diff - generated-tests/output38.txt
./allocate -f generated-tests/data39.txt -s RR -m best-fit -q 2 | diff - generated-tests/output39.txt
./allocate -f generated-tests/data40.txt -s RR -m best-fit -q 2 | diff - generated-tests/output40.txt
./allocate -f generated-tests/data41.txt -s RR -m infinite -q 2 | diff - generated-tests/output41.txt
./allocate -f generated-tests/data42.txt -s RR -m infinite -q 1 | diff - generated-tests/output42.txt
./allocate -f generated-tests/data43.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output43.txt
./allocate -f generated-tests/data44.txt -s RR -m infinite -q 2 | diff - generated-tests/output44.txt
./allocate -f generated-tests/data45.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output45.txt
./allocate -f generated-tests/data46.txt -s SJF -m infinite -q 2 | diff - generated-tests/output46.txt
./allocate -f generated-tests/data47.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output47.txt
./allocate -f generated-tests/data48.txt -s SJF -m infinite -q 3 | diff - generated-tests/output48.txt
./allocate -f generated-tests/data49.txt -s RR -m best-fit -q 2 | diff - generated-tests/output49.txt
./allocate -f generated-tests/data50.txt -s RR -m infinite -q 1 | diff - generated-tests/output50.txt
./allocate -f generated-tests/data51.txt -s RR -m infinite -q 3 | diff - generated-tests/output51.txt
./allocate -f generated-tests/data52.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output52.txt
./allocate -f generated-tests/data53.txt -s RR -m best-fit -q 3 | diff - generated-tests/output53.txt
./allocate -f generated-tests/data54.txt -s SJF -m best-fit -q 3 | diff - generated-tests/output54.txt
./allocate -f generated-tests/data55.txt -s SJF -m infinite -q 2 | diff - generated-tests/output55.txt
./allocate -f generated-tests/data56.txt -s SJF -m infinite -q 2 | diff - generated-tests/output56.txt
./allocate -f generated-tests/data57.txt -s RR -m infinite -q 1 | diff - generated-tests/output57.txt
./allocate -f generated-tests/data58.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output58.txt
./allocate -f generated-tests/data59.txt -s SJF -m best-fit -q 3 | diff - generated-tests/output59.txt
./allocate -f generated-tests/data60.txt -s RR -m best-fit -q 2 | diff - generated-tests/output60.txt
./allocate -f generated-tests/data61.txt -s SJF -m best-fit -q 3 | diff - generated-tests/output61.txt
./allocate -f generated-tests/data62.txt -s SJF -m infinite -q 2 | diff - generated-tests/output62.txt
./allocate -f generated-tests/data63.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output63.txt
./allocate -f generated-tests/data64.txt -s SJF -m infinite -q 2 | diff - generated-tests/output64.txt
./allocate -f generated-tests/data65.txt -s RR -m infinite -q 1 | diff - generated-tests/output65.txt
./allocate -f generated-tests/data66.txt -s RR -m infinite -q 3 | diff - generated-tests/output66.txt
./allocate -f generated-tests/data67.txt -s RR -m infinite -q 1 | diff - generated-tests/output67.txt
./allocate -f generated-tests/data68.txt -s RR -m infinite -q 3 | diff - generated-tests/output68.txt
./allocate -f generated-tests/data69.txt -s RR -m infinite -q 2 | diff - generated-tests/output69.txt
./allocate -f generated-tests/data70.txt -s RR -m infinite -q 2 | diff - generated-tests/output70.txt
./allocate -f generated-tests/data71.txt -s SJF -m infinite -q 3 | diff - generated-tests/output71.txt
./allocate -f generated-tests/data72.txt -s RR -m infinite -q 3 | diff - generated-tests/output72.txt
./allocate -f generated-tests/data73.txt -s SJF -m infinite -q 2 | diff - generated-tests/output73.txt
./allocate -f generated-tests/data74.txt -s SJF -m infinite -q 3 | diff - generated-tests/output74.txt
./allocate -f generated-tests/data75.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output75.txt
./allocate -f generated-tests/data76.txt -s SJF -m best-fit -q 1 | diff - generated-tests/output76.txt
./allocate -f generated-tests/data77.txt -s RR -m best-fit -q 3 | diff - generated-tests/output77.txt
./allocate -f generated-tests/data78.txt -s RR -m best-fit -q 3 | diff - generated-tests/output78.txt
./allocate -f generated-tests/data79.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output79.txt
./allocate -f generated-tests/data80.txt -s SJF -m best-fit -q 3 | diff - generated-tests/output80.txt
./allocate -f generated-tests/data81.txt -s RR -m infinite -q 3 | diff - generated-tests/output81.txt
./allocate -f generated-tests/data82.txt -s RR -m best-fit -q 3 | diff - generated-tests/output82.txt
./allocate -f generated-tests/data83.txt -s RR -m best-fit -q 3 | diff - generated-tests/output83.txt
./allocate -f generated-tests/data84.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output84.txt
./allocate -f generated-tests/data85.txt -s RR -m best-fit -q 2 | diff - generated-tests/output85.txt
./allocate -f generated-tests/data86.txt -s SJF -m infinite -q 3 | diff - generated-tests/output86.txt
./allocate -f generated-tests/data87.txt -s SJF -m infinite -q 1 | diff - generated-tests/output87.txt
./allocate -f generated-tests/data88.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output88.txt
./allocate -f generated-tests/data89.txt -s RR -m infinite -q 3 | diff - generated-tests/output89.txt
./allocate -f generated-tests/data90.txt -s RR -m infinite -q 1 | diff - generated-tests/output90.txt
./allocate -f generated-tests/data91.txt -s SJF -m infinite -q 1 | diff - generated-tests/output91.txt
./allocate -f generated-tests/data92.txt -s SJF -m best-fit -q 3 | diff - generated-tests/output92.txt
./allocate -f generated-tests/data93.txt -s RR -m best-fit -q 3 | diff - generated-tests/output93.txt
./allocate -f generated-tests/data94.txt -s RR -m best-fit -q 2 | diff - generated-tests/output94.txt
./allocate -f generated-tests/data95.txt -s SJF -m best-fit -q 2 | diff - generated-tests/output95.txt
./allocate -f generated-tests/data96.txt -s RR -m infinite -q 1 | diff - generated-tests/output96.txt
./allocate -f generated-tests/data97.txt -s RR -m infinite -q 3 | diff - generated-tests/output97.txt
./allocate -f generated-tests/data98.txt -s RR -m best-fit -q 3 | diff - generated-tests/output98.txt
./allocate -f generated-tests/data99.txt -s RR -m infinite -q 3 | diff - generated-tests/output99.txt
